version: '2.1'

services:

  albums-db:
    container_name: albums-db
    build: ./server/project/db
    volumes:
      - './server/project/db/:/usr/src/app/server/project/db'
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: exit 0

  albums-service:
    container_name: albums-service
    build: ./server
    ports:
      - '5000:5001'
    environment:
      - APP_SETTINGS=${APP_SETTINGS}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_TEST_URL=${DATABASE_TEST_URL}
      - REACT_APP_REDIRECT_URI=${REACT_APP_REDIRECT_URI}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
    depends_on:
      albums-db:
        condition: service_healthy
    links:
      - albums-db

  web-service:
    container_name: web-service
    build:
      context: ./client
      args:
        - REACT_APP_REDIRECT_URI=${REACT_APP_REDIRECT_URI}
        - REACT_APP_CLIENT_ID=${REACT_APP_CLIENT_ID}
    ports:
      - '9000:80'
    depends_on:
      albums-service:
        condition: service_started
    links:
      - albums-service

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - albums-service
      - web-service
