apiVersion: v1
kind: Service
metadata:
  name: photopostgres
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: photopostgres

---
apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    name: flask
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5000
    protocol: TCP
  selector:
    app: flask

---
apiVersion: v1
kind: Service
metadata:
  name: react
  labels:
    name: react
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
  selector:
    app: react

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
